# Configuration for orchestration stage
nodes:
  preprocessing: "../1_preprocessing/main.py"
  maelia_pipeline: "../2_maelia_pipeline/main.py"
  optimisation: "../3_optimisation/main.py"
  gama_multiagent: "../6_gama_multiagent/main.py"
  analysis_visualization: "../5_analysis_visualization/main.py"
settings:
  run_order:
    - preprocessing
    - maelia_pipeline
    - optimisation
    - gama_multiagent
    - analysis_visualization
