version: "3.8"

services:
  gama:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    volumes:
      - ../models:/workspace/models
      - ../tests:/workspace/tests
      - ../inputs:/workspace/inputs
      - ../gama_plugins:/workspace/gama_plugins

    working_dir: /workspace

    tty: true